name: AI Semantic Version Tagger

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  issues: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r .github/actions/requirements.txt

      - name: Create semantic version tag
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_PAT: ${{ secrets.REPO_PAT }}
        run: python .github/actions/semver_tagger.py
